---
meta:
  name:    eden
  target:  ohio-cf
  url:     https://ci-ohio.starkandwayne.com

  initial_version: 0.5.0

  go:
    binary: eden
    cmd_module: .

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  aws:
    bucket:      (( concat meta.pipeline "-pipeline" ))
    region_name: eu-central-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  starkandwayne
    repo:   eden
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel: "#eden" # https://openservicebrokerapi.slack.com/messages/C6Y5A2N8Z/
